# Use postgres/example user/password credentials
version: '3.8'

services:

  main_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    links:
      - shard1_db
      - shard2_db
    environment:
      POSTGRES_PASSWORD: main_db
    volumes:
      - ./main_db_init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - shard1_db
      - shard2_db

  shard1_db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: shard1_db
    volumes:
    - ./shard1_init.sql:/docker-entrypoint-initdb.d/init.sql

  shard2_db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: shard2_db
    volumes:
      - ./shard2_init.sql:/docker-entrypoint-initdb.d/init.sql

  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
    - 8080:8080
    depends_on:
      - main_db
    links:
      - main_db
  app2:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - main_db
    links:
      - main_db
  app3:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - main_db
    links:
      - main_db



